# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Setup Node, pnpm, cache & install"
description: "Setup Node, Pnpm, Cache & Install"
branding:
  icon: package
  color: orange
inputs:
  node-version:
    description: "Version of Node"
    required: false
    default: 18.x
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      name: Install pnpm
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4.0.0
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
