# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Setup Node, pnpm, cache & install"
description: "Setup Node, Pnpm, Cache & Install"
branding:
  icon: package
  color: orange
inputs:
  node-version:
    description: "Version of Node"
    required: false
    default: 20.x
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #v4.2.0
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install
