# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Setup Node, pnpm, cache & install"
description: "Setup Node, Pnpm, Cache & Install"
branding:
  icon: package
  color: orange
inputs:
  node-version:
    description: "Version of Node"
    required: false
    default: 20.x
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4.0.0
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install
