# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: "Setup Node, pnpm, cache & install"
description: "Setup Node, Pnpm, Cache & Install"
branding:
  icon: package
  color: orange
inputs:
  node-version:
    description: "Version of Node"
    required: false
    default: 20.x
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 #v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install
